export interface EventData {
    slug: string
    title: string
    category: string
    location: string
    year: string
    img: string           // card thumbnail
    imgPosition?: string  // CSS object-position for card crop (default: center center)
    imgScale?: number     // initial zoom on card thumbnail (default: 1)
    imgRotate?: number    // rotation in degrees (positive = clockwise)
    bgImg?: string        // project page background (falls back to img if not set)
    stripImg?: string     // homepage film strip image (falls back to img if not set)
    stripPosition?: string // CSS object-position for the strip crop
    heroImg: string | null  // expanding center image (null = placeholder)
    gallery: (string | null)[]  // videos + photos
    featuredVideo?: string    // optional full-width feature video shown below reels
    description: string
    storyboard?: string       // optional storyboard/moodboard image
    storyboardCaption?: string
    partnershipBadge?: string  // if set, shows a gold trust badge with custom text
    yearSections?: { year: string; video: string }[]  // multi-year projects: each year gets its own video section
    featuredVideos?: string[]  // multiple full-width videos stacked vertically
}

export const events: EventData[] = [
    {
        slug: 'sckylers',
        title: 'Sckylers',
        category: 'Real Estate',
        location: 'Cairo JW Marriott',
        year: '2025',
        img: '/event photos/Sckylers/20250904-20250903-DSC09464.JPG',
        heroImg: '/event photos/Sckylers/Old/Sckylers.003.jpeg',
        gallery: [
            // ── Videos (reels strip) ──
            '/event videos/Sckylers/SCKYLERS FINAL .mp4',
            '/event videos/Sckylers/sckylers recap 2.mp4',
            '/event videos/Sckylers/sckylers Story 3.mp4',
            '/event videos/Sckylers/sckylers Story 5.mp4',
            // ── Stage / Production ──
            '/event photos/Sckylers/20250904-20250903-DSC08538.JPG',
            '/event photos/Sckylers/20250904-20250903-DSC08563.JPEG',
            '/event photos/Sckylers/20250904-20250903-DSC08587.JPEG',
            '/event photos/Sckylers/20250904-20250903-DSC09425.JPG',
            '/event photos/Sckylers/20250904-20250903-DSC09464.JPG',
            '/event photos/Sckylers/20250904-20250903-DSC09518.JPEG',
            '/event photos/Sckylers/20250904-20250903-DSC09582.JPG',
            // ── Crowd / Atmosphere ──
            '/event photos/Sckylers/sckylers-86.JPG',
            '/event photos/Sckylers/sckylers-87.JPG',
            '/event photos/Sckylers/sckylers-96.JPG',
            '/event photos/Sckylers/sckylers-120.JPG',
            '/event photos/Sckylers/sckylers-125.JPG',
            '/event photos/Sckylers/sckylers-139.JPEG',
            '/event photos/Sckylers/sckylers-141.JPG',
            '/event photos/Sckylers/sckylers-142.JPG',
            '/event photos/Sckylers/sckylers-142.JPEG',
            '/event photos/Sckylers/sckylers-143.JPEG',
            '/event photos/Sckylers/sckylers-145.JPEG',
            '/event photos/Sckylers/sckylers-146.JPG',
            '/event photos/Sckylers/sckylers-174.JPG',
            '/event photos/Sckylers/sckylers-192.JPG',
            '/event photos/Sckylers/sckylers-196.JPG',
            '/event photos/Sckylers/sckylers-new-1.jpg',
            '/event photos/Sckylers/sckylers-new-2.jpg',
            '/event photos/Sckylers/sckylers-new-3.jpg',
            '/event photos/Sckylers/sckylers-new-4.jpg',
        ],
        description: "A landmark project launch bringing together industry leaders for an unforgettable evening of unveiling and celebration at Cairo's iconic JW Marriott.",
    },
    {
        slug: 'wegovy',
        title: 'Wegovy',
        category: 'Pharma',
        location: 'Cairo JW Marriott',
        year: '2026',
        img: '/event photos/Wegovy/Wegovy.001.jpeg',
        heroImg: '/event photos/Wegovy/Wegovy.002.jpeg',
        featuredVideo: '/event videos/Wegovy/WEGOVY_Aftermovie_V10_Horizontal.MP4',
        gallery: [
            // ── Reels ──
            '/event videos/Wegovy/wegovy-1.mp4',
            '/event videos/Wegovy/wegovy-2.mp4',
            '/event videos/Wegovy/wegovy-3.mp4',
            '/event videos/Wegovy/wegovy-4.mp4',
            // ── Entrance & Branding ──
            '/event photos/Wegovy/Wegovy.004.jpeg',
            '/event photos/Wegovy/Wegovy.006.jpeg',
            '/event photos/Wegovy/wegovy-photo-04.png',
            '/event photos/Wegovy/Wegovy.007.jpeg',
            '/event photos/Wegovy/wegovy-photo-05.png',
            // ── Stage & Presentation ──
            '/event photos/Wegovy/wegovy-photo-06.png',
            '/event photos/Wegovy/Wegovy.005.jpeg',
            '/event photos/Wegovy/wegovy-photo-10.png',
            '/event photos/Wegovy/wegovy-performers-002.jpeg',
            '/event photos/Wegovy/Wegovy.002.jpeg',
            '/event photos/Wegovy/Wegovy.003.jpeg',
            // ── Entertainment & Performance ──
            '/event photos/Wegovy/wegovy-photo-01.png',
            '/event photos/Wegovy/wegovy-photo-08.png',
            '/event photos/Wegovy/wegovy-photo-07.png',
            '/event photos/Wegovy/wegovy-photo-02.png',
            '/event photos/Wegovy/wegovy-performers-0001.png',
            '/event photos/Wegovy/Wegovy.001.jpeg',
            '/event photos/Wegovy/wegovy-performers-000.png',
            '/event photos/Wegovy/wegovy-photo-09.png',
            // ── Finale ──
            '/event photos/Wegovy/wegovy-photo-03.png',
            '/event photos/Wegovy/wegovy-photo-11.png',
        ],
        description: 'A high-impact pharmaceutical product launch designed to educate, inspire, and captivate medical professionals across the region.',
        storyboard: '/event photos/Wegovy/storyboard.jpg',
        storyboardCaption: 'Creative Brief · Pre-Production Storyboard',
    },
    {
        slug: 'wegovy-tour-montaza',
        title: 'Wegovy Tour — Montaza',
        category: 'Pharma',
        location: 'Montaza, Alexandria',
        year: '2026',
        img: '/event photos/Wegovy Tour - Montaza/Wegovy_Montaza_Card-new.png',
        bgImg: '/event photos/Wegovy Tour - Montaza/Wegovy_Montaza_Card-new.png',
        heroImg: '/event photos/Wegovy Tour - Montaza/Wegovy_Montaza_scroll.png',
        featuredVideo: '/event videos/Wegovy Tour - Montaza/Wegovy_Alex_Recap_V05.mp4',
        gallery: [
            // ── Gate & Entrance ──
            '/event photos/Wegovy Tour - Montaza/photo-08.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-12.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-19.jpg',
            // ── Logo & Branding ──
            '/event photos/Wegovy Tour - Montaza/photo-11.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-13.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-14.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-15.jpg',
            // ── Production Setup ──
            '/event photos/Wegovy Tour - Montaza/photo-23.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-24.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-22.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-25.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-07.jpg',
            // ── Speakers ──
            '/event photos/Wegovy Tour - Montaza/photo-17.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-18.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-20.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-21.jpg',
            // ── Stage & Event ──
            '/event photos/Wegovy Tour - Montaza/photo-03.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-04.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-16.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-26.jpg',
            // ── Aerial Shots ──
            '/event photos/Wegovy Tour - Montaza/photo-10.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-09.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-02.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-05.jpg',
            '/event photos/Wegovy Tour - Montaza/photo-06.jpg',
            // ── Reels ──
            '/event videos/Wegovy Tour - Montaza/Story 1.mp4',
            '/event videos/Wegovy Tour - Montaza/Story_3.mp4',
            '/event videos/Wegovy Tour - Montaza/Story_06-7.mp4',
            '/event videos/Wegovy Tour - Montaza/Story_08.mp4',
            '/event videos/Wegovy Tour - Montaza/Story_11.mp4',
            '/event videos/Wegovy Tour - Montaza/Story_12.mp4',
            '/event videos/Wegovy Tour - Montaza/Story_13.mp4',
            '/event videos/Wegovy Tour - Montaza/Story_14_V02.mp4',
        ],
        description: 'The Wegovy roadshow takes to the Alexandria coast — an outdoor brand activation at the iconic Montaza Palace grounds, bringing the Wegovy experience to a new audience along the Mediterranean.',
    },
    {
        slug: 'lipton-appreciation-event',
        title: 'Lipton Appreciation Event',
        category: 'FMCG',
        location: 'Cairo — Mohamed Aly Castle',
        year: '2023',
        img: '/event photos/Lipton Appreciation Event/Lipton_15.png',
        bgImg: '/event photos/Lipton Appreciation Event/Lipton_15.png',
        heroImg: '/event photos/Lipton Appreciation Event/0P9A1321_web.jpg',
        featuredVideo: '/event videos/Lipton Appreciation Event/7-5 lipton event-.mp4',
        gallery: [
'/event photos/Lipton Appreciation Event/0P9A0216.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0223.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0229.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0237.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0271.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0286.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0292.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0294.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0307.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0316.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0363.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0373.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0384.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0391.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0411.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0424.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0446.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0450.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0468.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0486.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0494.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0504.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0508.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0561.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0570.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0605.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0649.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0715.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0720.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0723.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0738.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0773.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0785.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0788.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0862.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0875.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0879.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0960.jpg',
            '/event photos/Lipton Appreciation Event/0P9A0977.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1002.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1023.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1086.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1227.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1313.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1321.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1326.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1329.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1377.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1386.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1406.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1408.jpg',
            '/event photos/Lipton Appreciation Event/0P9A1424.jpg',
            '/event photos/Lipton Appreciation Event/BA6A5439.jpg',
            '/event photos/Lipton Appreciation Event/BA6A5587.jpg',
            '/event photos/Lipton Appreciation Event/BA6A5592.jpg',
            '/event photos/Lipton Appreciation Event/Lipton_1.png',
            '/event photos/Lipton Appreciation Event/Lipton_2.png',
            '/event photos/Lipton Appreciation Event/Lipton_3.png',
            '/event photos/Lipton Appreciation Event/Lipton_4.png',
            '/event photos/Lipton Appreciation Event/Lipton_5.png',
            '/event photos/Lipton Appreciation Event/Lipton_6.png',
            '/event photos/Lipton Appreciation Event/Lipton_7.png',
            '/event photos/Lipton Appreciation Event/Lipton_8.png',
            '/event photos/Lipton Appreciation Event/Lipton_9.png',
            '/event photos/Lipton Appreciation Event/Lipton_10.png',
            '/event photos/Lipton Appreciation Event/Lipton_11.png',
            '/event photos/Lipton Appreciation Event/Lipton_12.png',
            '/event photos/Lipton Appreciation Event/Lipton_13.png',
            '/event photos/Lipton Appreciation Event/Lipton_14.png',
            '/event photos/Lipton Appreciation Event/Lipton_15.png',
            '/event photos/Lipton Appreciation Event/Lipton_16.png',
        ],
        description: 'An elegant appreciation gala for Lipton Teas & Infusions — honoring top performers in a spectacular palace setting with live entertainment, awards, and a night of recognition that felt anything but ordinary.',
    },
    {
        slug: 'wegovy-tour-citadel-saladin',
        title: 'Wegovy Tour — Citadel Saladin',
        category: 'Pharma',
        location: 'Citadel of Saladin, Cairo',
        year: '2026',
        img: '/event photos/Wegovt Tour - Citadel Saladin/photo-01_fixed.jpg',
        bgImg: '/event photos/Wegovt Tour - Citadel Saladin/photo-01_fixed.jpg',
        heroImg: '/event photos/Wegovt Tour - Citadel Saladin/photo-18_fixed.jpg',
        featuredVideo: '/event videos/Wegovt Tour - Citadel Saladin/WEGOVY_CITADEL_V01.mp4',
        gallery: [
            // ── Story Reels ──
            '/event videos/Wegovt Tour - Citadel Saladin/S01_V01.mp4',
            '/event videos/Wegovt Tour - Citadel Saladin/S03_V01.mp4',
            '/event videos/Wegovt Tour - Citadel Saladin/S05_V01.mp4',
            '/event videos/Wegovt Tour - Citadel Saladin/S06+S07_V01.mp4',
            '/event videos/Wegovt Tour - Citadel Saladin/S09+S10+S11_V01.mp4',
            '/event videos/Wegovt Tour - Citadel Saladin/S12-FIANLE.mp4',
            // ── Photos ──
            '/event photos/Wegovt Tour - Citadel Saladin/photo-01_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-02_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-03_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-04_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-05_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-06_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-07_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-08_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-09_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-10_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-11_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-12_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-13_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-14_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-15_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-16_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-17_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-18_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-19_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-20_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-21_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-22_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-23_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-24_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-25_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-26_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-27_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-28_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-29_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-30_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-31_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-32_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-33_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-34_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-35_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-36_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-37_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-38_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-39_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-40_fixed.jpg',
            '/event photos/Wegovt Tour - Citadel Saladin/photo-41_fixed.jpg',
        ],
        description: 'The Wegovy Tour arrives at one of Cairo\'s most iconic landmarks — the historic Citadel of Saladin. A landmark brand experience set against centuries of heritage, bringing modern healthcare innovation to an unforgettable backdrop.',
    },
    {
        slug: 'marriott-residence',
        title: 'Marriott Residence',
        category: 'Real Estate',
        location: 'Cairo Marriott Premises',
        year: '2025',
        img: '/event photos/Marriot Residence/Marriot new/Marriot Photo 5.jpg',
        bgImg: '/event photos/Marriot Residence/Marriot new/Marriot new.008jpeg.png',
        heroImg: '/event photos/Marriot Residence/Marriot new/Marriot new.002.jpeg',
        gallery: [
            // ── Videos (reels strip) ──
            '/event videos/Marriot Residence/Marriot new/Marriot Video 1.mp4',
            '/event videos/Marriot Residence/Marriot new/Marriot Video 2.mp4',
            '/event videos/Marriot Residence/Marriot new/Marriot Video 3.mp4',
            '/event videos/Marriot Residence/Marriot new/Marriot Video 4.mp4',
            '/event videos/Marriot Residence/Marriot new/Marriot Video 5.mp4',
            '/event videos/Marriot Residence/Marriot new/Marriot Video 6.mp4',
            // ── Photos ──
            '/event photos/Marriot Residence/Marriot new/Marriot Photo 1.jpg',
            '/event photos/Marriot Residence/Marriot new/Marriot Photo 2.jpg',
            '/event photos/Marriot Residence/Marriot new/Marriot Photo 3.jpg',
            '/event photos/Marriot Residence/Marriot new/Marriot Photo 4.jpg',
            '/event photos/Marriot Residence/Marriot new/Marriot Photo 5.jpg',
            '/event photos/Marriot Residence/Marriot new/Marriot Photo 6.jpg',
            '/event photos/Marriot Residence/Marriot new/Marriot Photo 7.jpg',
            '/event photos/Marriot Residence/Marriot new/Marriot Photo 8.jpg',
            '/event photos/Marriot Residence/Marriot new/Marriot new.001.jpeg',
            '/event photos/Marriot Residence/Marriot new/Marriot new.002.jpeg',
            '/event photos/Marriot Residence/Marriot new/Marriot new.003.jpeg',
            '/event photos/Marriot Residence/Marriot new/Marriot new.004.jpeg',
            '/event photos/Marriot Residence/Marriot new/Marriot new.005.jpeg',
            '/event photos/Marriot Residence/Marriot new/Marriot new.006.jpeg',
            '/event photos/Marriot Residence/Marriot new/Marriot new.007.jpeg',
        ],
        description: 'An exclusive residential launch event crafted to showcase luxury living at the heart of Cairo, elegant, refined, and meticulously produced.',
    },
    {
        slug: 'arabtec',
        title: 'Arabtec',
        category: 'Milestone Celebration',
        location: 'Cairo — The Grand Museum of Egypt',
        year: '2025',
        img: '/event photos/Arabtec/0P9A8044.jpg',
        imgScale: 1.4,
        imgPosition: 'center 75%',
        bgImg: '/event photos/Arabtec/DSC00665.jpg',
        heroImg: '/event photos/Arabtec/DSC00665.jpg',
        gallery: [
            // ── Video ──
            '/event videos/Arabtec/arabtec video.mp4',
            // ── Opening Shots ──
            '/event photos/Arabtec/0P9A7785.jpg',
            '/event photos/Arabtec/KORY9029.jpg',
            // ── Cars ──
            '/event photos/Arabtec/DSC00382.JPG',
            // ── Arrivals ──
            '/event photos/Arabtec/GRGS4465.jpg',
            '/event photos/Arabtec/KORY9126.jpg',
            '/event photos/Arabtec/DSC00843.jpg',
            '/event photos/Arabtec/KORY9073.jpg',
            '/event photos/Arabtec/KORY9092.jpg',
            '/event photos/Arabtec/0P9A8129.jpg',
            // ── Branding & Walls ──
            '/event photos/Arabtec/GRGS4382.JPG',

            '/event photos/Arabtec/DSC00884.jpg',
            '/event photos/Arabtec/KORY9042.jpg',
            '/event photos/Arabtec/KORY9286.jpg',
            '/event photos/Arabtec/KORY9287.jpg',
            '/event photos/Arabtec/DSC00378.JPG',
            // ── Stage & LED Screens ──
            '/event photos/Arabtec/DSC00609.JPG',
            '/event photos/Arabtec/GRGS4394.JPG',
            '/event photos/Arabtec/KORY9022.jpg',
            '/event photos/Arabtec/0P9A7836.jpg',
            '/event photos/Arabtec/0P9A8044.jpg',
            // ── Food ──
            '/event photos/Arabtec/DSC00315.JPG',
            '/event photos/Arabtec/GRGS4390.JPG',
            '/event photos/Arabtec/KORY9001.jpg',
            '/event photos/Arabtec/0P9A7973.jpg',
            // ── Entertainment ──
            '/event photos/Arabtec/DSC00767.jpg',
            '/event photos/Arabtec/GRGS4431.jpg',
            '/event photos/Arabtec/GRGS5018.jpg',
            // ── People Engagement ──
            '/event photos/Arabtec/DSC00621.jpg',
            '/event photos/Arabtec/DSC00647.jpg',
            '/event photos/Arabtec/DSC00659.jpg',
            '/event photos/Arabtec/DSC00665.jpg',
            '/event photos/Arabtec/GRGS4867.jpg',
            '/event photos/Arabtec/DSC00616.jpg',
            '/event photos/Arabtec/GRGS4637.jpg',
            '/event photos/Arabtec/0P9A7778.jpg',
            '/event photos/Arabtec/0P9A7797.jpg',
            '/event photos/Arabtec/KORY9257.jpg',
            '/event photos/Arabtec/GRGS4439.jpg',
            '/event photos/Arabtec/GRGS4943.jpg',
        ],
        description: 'A high-profile corporate event produced for Arabtec, bringing together industry leaders and stakeholders in a meticulously designed environment that reflects ambition and precision.',
    },
    {
        slug: 'hometown',
        title: 'Hometown Project',
        category: 'Real Estate',
        location: 'New Cairo — St. Regis Hotel',
        year: '2025',
        img: '/event photos/Home Town/US501930.JPG',
        heroImg: '/event photos/Home Town/Scroll.JPG',
        gallery: [
            // ── Videos ──
            '/event videos/Home Town/Home Town.mp4',
            // ── Opening ──
            '/event photos/Home Town/GRGS7575.jpg',
            '/event photos/Home Town/US501929.JPG',
            '/event photos/Home Town/US501930.JPG',
            // ── Branding & Entrance ──
            '/event photos/Home Town/US501057.JPG',
            '/event photos/Home Town/031A7177.jpg',
            '/event photos/Home Town/031A7156.jpg',
            // ── Arrivals & Experience ──
            '/event photos/Home Town/US501975.JPG',
            '/event photos/Home Town/US501976.JPG',
            '/event photos/Home Town/031A7237.jpg',
            // ── Stage & Production ──
            '/event photos/Home Town/Scroll.JPG',
            '/event photos/Home Town/Main.JPG',
            '/event photos/Home Town/A13A4411.JPG',
            '/event photos/Home Town/A13A4101.JPG',
            // ── Presentations ──
            '/event photos/Home Town/GRGS7611.jpg',
            // ── Entertainment & Launch ──
            '/event photos/Home Town/A13A4351.JPG',
            '/event photos/Home Town/A13A5143.JPG',
            '/event photos/Home Town/GRGS7769.jpg',
            '/event photos/Home Town/A13A5048.JPG',
            '/event photos/Home Town/GRGS7864.jpg',
        ],
        description: 'A spectacular real-estate launch event for Hometown Developments — an immersive experience that brought Home Residence New Cairo to life through world-class production, live entertainment, and captivating brand storytelling.',
    },
    {
        slug: 'ozempic',
        title: 'Ozempic Launch',
        category: 'Pharma',
        location: 'Cairo — JW Marriott',
        year: '2025',
        img: '/event photos/Ozempic/Ozempic 1.png',
        heroImg: '/event photos/Ozempic/image63.jpeg',
        gallery: [
            // ── Video ──
            '/event videos/Ozempic/Ozempic event-.mp4',
            // ── Ozempic Brand Shots ──
            '/event photos/Ozempic/Ozempic 1.png',
            '/event photos/Ozempic/Ozempic 2.png',
            '/event photos/Ozempic/Ozempic 3.png',
            // ── Birdeye ──
            '/event photos/Ozempic/Birdeye Ozempic 3.png',
            '/event photos/Ozempic/Birdeye Ozempic.png',
            '/event photos/Ozempic/Birdeye Ozempic 2.png',
            // ── Entrance & Branding ──
            '/event photos/Ozempic/ZrNzNuoQ.jpg',
            '/event photos/Ozempic/YKmbyHPI.jpg',
            '/event photos/Ozempic/YASS0907.jpg',
            // ── Ozempic Detail Shots ──
            '/event photos/Ozempic/Ozempic 4.png',
            '/event photos/Ozempic/Ozempic 5.png',
            '/event photos/Ozempic/Ozempic 6.png',
            // ── Stage & Presentations ──
            '/event photos/Ozempic/AO5u79a8.jpg',
            '/event photos/Ozempic/455e0287-ab07-406a-a471-2cd2029f4bec.JPG',
            '/event photos/Ozempic/YASS0294.jpg',
            '/event photos/Ozempic/image57.jpeg',
            '/event photos/Ozempic/image56.jpeg',
            '/event photos/Ozempic/YASS0245.jpg',
            // ── Torch & Speakers ──
            '/event photos/Ozempic/YASS0182.jpg',
            '/event photos/Ozempic/YASS0196.jpg',
            '/event photos/Ozempic/YASS0238.jpg',
            '/event photos/Ozempic/YASS0436.jpg',
            '/event photos/Ozempic/YASS0564.jpg',
            '/event photos/Ozempic/tj01iiY8.jpg',
            '/event photos/Ozempic/YASS0135.jpg',
            // ── Product Reveal — full-width sequence (must stay as last 4) ──
            '/event photos/Ozempic/YASS0794.jpg',
            '/event photos/Ozempic/YASS0798.jpg',
            '/event photos/Ozempic/image62.jpeg',
            '/event photos/Ozempic/image63.jpeg',
        ],
        description: "A landmark pharmaceutical launch event introducing Ozempic to Egypt — an outdoor spectacle of light, sound, and storytelling that brought Novo Nordisk's vision of 'Realise the Potential' to life with world-class production and a powerful reveal moment.",
    },
    {
        slug: 'food-bank',
        title: 'Egyptian Food Bank',
        category: 'Milestone Celebration',
        location: 'Cairo — The Grand Museum of Egypt',
        year: '2025',
        img: '/event photos/Food Bank/YASS2677.jpg',
        heroImg: '/event photos/Food Bank/YASS2786.jpg',
        gallery: [
            // ── Video ──
            '/event videos/Food Bank/RECAP BANK FOOD.mp4',
            // ── All Photos ──
            '/event photos/Food Bank/Card.jpg',
            '/event photos/Food Bank/scrolling.jpg',
            '/event photos/Food Bank/DSC06637.JPG',
            '/event photos/Food Bank/DSC06640.JPG',
            '/event photos/Food Bank/DSC06642.JPG',
            '/event photos/Food Bank/DSC06650.JPG',
            '/event photos/Food Bank/DSC06660.JPG',
            '/event photos/Food Bank/DSC06663.JPG',
            '/event photos/Food Bank/DSC06666.JPG',
            '/event photos/Food Bank/DSC06672.JPG',
            '/event photos/Food Bank/DSC06712.jpg',
            '/event photos/Food Bank/DSC06789.jpg',
            '/event photos/Food Bank/DSC06819.jpg',
            '/event photos/Food Bank/DSC06827.jpg',
            '/event photos/Food Bank/DSC06831.jpg',
            '/event photos/Food Bank/DSC06857.jpg',
            '/event photos/Food Bank/DSC06875.jpg',
            '/event photos/Food Bank/DSC06981.jpg',
            '/event photos/Food Bank/DSC07021.jpg',
            '/event photos/Food Bank/DSC07059.jpg',
            '/event photos/Food Bank/DSC07070.jpg',
            '/event photos/Food Bank/DSC07088.jpg',
            '/event photos/Food Bank/DSC07089.jpg',
            '/event photos/Food Bank/DSC07102.jpg',
            '/event photos/Food Bank/DSC07107.jpg',
            '/event photos/Food Bank/DSC07119.jpg',
            '/event photos/Food Bank/DSC07212.jpg',
            '/event photos/Food Bank/DSC07269.jpg',
            '/event photos/Food Bank/DSC07310.jpg',
            '/event photos/Food Bank/DSC07317.jpg',
            '/event photos/Food Bank/DSC07527.jpg',
            '/event photos/Food Bank/DSC07554.jpg',
            '/event photos/Food Bank/DSC07556.jpg',
            '/event photos/Food Bank/DSC07569.jpg',
            '/event photos/Food Bank/DSC07598.jpg',
            '/event photos/Food Bank/DSC07635.jpg',
            '/event photos/Food Bank/DSC07686.jpg',
            '/event photos/Food Bank/DSC07696.jpg',
            '/event photos/Food Bank/DSC07734.jpg',
            '/event photos/Food Bank/DSC07765.jpg',
            '/event photos/Food Bank/DSC07769.jpg',
            '/event photos/Food Bank/DSC07808.jpg',
            '/event photos/Food Bank/DSC07820.jpg',
            '/event photos/Food Bank/DSC07847.jpg',
            '/event photos/Food Bank/DSC07942.jpg',
            '/event photos/Food Bank/DSC07950.jpg',
            '/event photos/Food Bank/DSC07985.jpg',
            '/event photos/Food Bank/DSC08029.jpg',
            '/event photos/Food Bank/DSC08077.jpg',
            '/event photos/Food Bank/DSC08117.jpg',
            '/event photos/Food Bank/DSC08144.jpg',
            '/event photos/Food Bank/DSC08170.jpg',
            '/event photos/Food Bank/DSC08196.jpg',
            '/event photos/Food Bank/DSC08216.jpg',
            '/event photos/Food Bank/DSC08286.jpg',
            '/event photos/Food Bank/DSC08349.jpg',
            '/event photos/Food Bank/DSC08367.jpg',
            '/event photos/Food Bank/DSC08371.jpg',
            '/event photos/Food Bank/YASS2334.jpg',
            '/event photos/Food Bank/YASS2337.jpg',
            '/event photos/Food Bank/YASS2338.jpg',
            '/event photos/Food Bank/YASS2343.jpg',
            '/event photos/Food Bank/YASS2347.jpg',
            '/event photos/Food Bank/YASS2349.jpg',
            '/event photos/Food Bank/YASS2351.jpg',
            '/event photos/Food Bank/YASS2359.jpg',
            '/event photos/Food Bank/YASS2360.jpg',
            '/event photos/Food Bank/YASS2361.jpg',
            '/event photos/Food Bank/YASS2370.jpg',
            '/event photos/Food Bank/YASS2419.jpg',
            '/event photos/Food Bank/YASS2456.jpg',
            '/event photos/Food Bank/YASS2469.jpg',
            '/event photos/Food Bank/YASS2512.jpg',
            '/event photos/Food Bank/YASS2517.jpg',
            '/event photos/Food Bank/YASS2524.jpg',
            '/event photos/Food Bank/YASS2538.jpg',
            '/event photos/Food Bank/YASS2549.jpg',
            '/event photos/Food Bank/YASS2551.jpg',
            '/event photos/Food Bank/YASS2552.jpg',
            '/event photos/Food Bank/YASS2554.jpg',
            '/event photos/Food Bank/YASS2555.jpg',
            '/event photos/Food Bank/YASS2559.jpg',
            '/event photos/Food Bank/YASS2560.jpg',
            '/event photos/Food Bank/YASS2561.jpg',
            '/event photos/Food Bank/YASS2578.jpg',
            '/event photos/Food Bank/YASS2584.jpg',
            '/event photos/Food Bank/YASS2592.jpg',
            '/event photos/Food Bank/YASS2593.jpg',
            '/event photos/Food Bank/YASS2597.jpg',
            '/event photos/Food Bank/YASS2599.jpg',
            '/event photos/Food Bank/YASS2600.jpg',
            '/event photos/Food Bank/YASS2608.jpg',
            '/event photos/Food Bank/YASS2610.jpg',
            '/event photos/Food Bank/YASS2613.jpg',
            '/event photos/Food Bank/YASS2648.jpg',
            '/event photos/Food Bank/YASS2677.jpg',
            '/event photos/Food Bank/YASS2702.jpg',
            '/event photos/Food Bank/YASS2711.jpg',
            '/event photos/Food Bank/YASS2727.jpg',
            '/event photos/Food Bank/YASS2786-2.jpg',
            '/event photos/Food Bank/YASS2786.jpg',
            '/event photos/Food Bank/YASS2797.jpg',
            '/event photos/Food Bank/YASS2817.jpg',
            '/event photos/Food Bank/YASS2840.jpg',
            '/event photos/Food Bank/YASS2859.jpg',
            '/event photos/Food Bank/YASS2884.jpg',
            '/event photos/Food Bank/YASS2904.jpg',
            '/event photos/Food Bank/YASS2953.jpg',
            '/event photos/Food Bank/YASS2961.jpg',
            '/event photos/Food Bank/YASS2988.jpg',
            '/event photos/Food Bank/YASS3029.jpg',
            '/event photos/Food Bank/YASS3055.jpg',
            '/event photos/Food Bank/YASS3110.jpg',
            '/event photos/Food Bank/YASS3129-2.jpg',
            '/event photos/Food Bank/YASS3129.jpg',
            '/event photos/Food Bank/YASS3135.jpg',
            '/event photos/Food Bank/YASS3163.jpg',
            '/event photos/Food Bank/YASS3196.jpg',
            '/event photos/Food Bank/YASS3259.jpg',
            '/event photos/Food Bank/YASS3262.jpg',
            '/event photos/Food Bank/YASS3264.jpg',
            '/event photos/Food Bank/YASS3302.jpg',
            '/event photos/Food Bank/YASS3307.jpg',
            '/event photos/Food Bank/YASS3309.jpg',
            '/event photos/Food Bank/YASS3311.jpg',
            '/event photos/Food Bank/YASS3373.jpg',
            '/event photos/Food Bank/YASS3384.jpg',
            '/event photos/Food Bank/YASS3390.jpg',
            '/event photos/Food Bank/YASS3393.jpg',
            '/event photos/Food Bank/YASS3405.jpg',
            '/event photos/Food Bank/YASS3424.jpg',
            '/event photos/Food Bank/YASS3427.jpg',
        ],
        description: "A prestigious gala dinner for the Egyptian Food Bank's Circle of Humanity initiative — an evening of purpose, recognition, and world-class entertainment that united Egypt's most influential figures around a shared mission of innovation for humanity.",
    },
    {
        slug: 'british-embassy',
        title: 'British Embassy — Royal Birthday Reception',
        category: 'Diplomatic Reception',
        location: 'British Embassy',
        year: '2025',
        partnershipBadge: 'Trusted Partner Since 2015',
        img: '/event photos/British/Main Photo.png',
        heroImg: '/event photos/British/19-20-2025 British Emabssy -208.jpg',
        gallery: [
            // ── Videos (shown first as reels) ──
            '/event videos/British/KBP reel 2.mp4',
            '/event videos/British/KBP reel 3.mp4',
            '/event videos/British/SnapInsta.to_AQOFVtmyki2RfCsAzDnlBXnwM7E-zqBURdWFP7WZT1frPohfy9R11pm8phx5YVofPEtxOKVna9mGnP9sYHWUaVpMJyQ8FyO18sJPQgY.mp4',
            // ── Production / Stage ──
            '/event photos/British/1Y6A2383.jpg',
            '/event photos/British/1Y6A2525.jpg',
            '/event photos/British/1Y6A2551.jpg',
            '/event photos/British/1Y6A2590.jpg',
            '/event photos/British/1Y6A2613.jpg',
            '/event photos/British/19-20-2025 British Emabssy -327.jpg',
            '/event photos/British/19-20-2025 British Emabssy -369.jpg',
            '/event photos/British/19-20-2025 British Emabssy -372.jpg',
            '/event photos/British/19-20-2025 British Emabssy -454.jpg',
            // ── Journey ──
            '/event photos/British/19-20-2025 British Emabssy -5.jpg',
            '/event photos/British/19-20-2025 British Emabssy -28.jpg',
            '/event photos/British/19-20-2025 British Emabssy -37.jpg',
            '/event photos/British/19-20-2025 British Emabssy -170.jpg',
            '/event photos/British/19-20-2025 British Emabssy -182.jpg',
            '/event photos/British/19-20-2025 British Emabssy -208.jpg',
            '/event photos/British/19-20-2025 British Emabssy -456.jpg',
            '/event photos/British/19-20-2025 British Emabssy -476.jpg',
            '/event photos/British/1Y6A2131-2.jpg',
            '/event photos/British/1Y6A2146.jpg',
            '/event photos/British/1Y6A2150.jpg',
            '/event photos/British/1Y6A2167-2.jpg',
            '/event photos/British/1Y6A2207.jpg',
            '/event photos/British/1Y6A2221.jpg',
            // ── Networking (faces — portrait ratio in grid) ──
            '/event photos/British/An exceptional gathering of esteemed guests came together at the British Embassy in Cairo to hon.jpg',
            '/event photos/British/An exceptional gathering of esteemed guests came together at the British Embassy in Cairo to hon-2.jpg',
            '/event photos/British/An exceptional gathering of esteemed guests came together at the British Embassy in Cairo to hon-6.jpg',
            '/event photos/British/An exceptional gathering of esteemed guests came together at the British Embassy in Cairo to hon-10.jpg',
            '/event photos/British/An exceptional gathering of esteemed guests came together at the British Embassy in Cairo to hon-11.jpg',
            '/event photos/British/An exceptional gathering of esteemed guests came together at the British Embassy in Cairo to hon-12.jpg',
            '/event photos/British/An exceptional gathering of esteemed guests came together at the British Embassy in Cairo to hon-14.jpg',
            '/event photos/British/An exceptional gathering of esteemed guests came together at the British Embassy in Cairo to hon-17.jpg',
            '/event photos/British/An exceptional gathering of esteemed guests came together at the British Embassy in Cairo to hon-18.jpg',
            '/event photos/British/An exceptional gathering of esteemed guests came together at the British Embassy in Cairo to hon-19.jpg',
            '/event photos/British/An exceptional gathering of esteemed guests came together at the British Embassy in Cairo to hon-20.jpg',
            '/event photos/British/UK (27).jpg',
            '/event photos/British/UK (50).jpg',
            '/event photos/British/UK (60).jpg',
            '/event photos/British/UK (132).jpg',
            '/event photos/British/UK (164).jpg',
            '/event photos/British/UK (405).jpg',
            '/event photos/British/UK (456).jpg',
            '/event photos/British/UK (475).jpg',
        ],
        description: "A prestigious royal reception honoring the King's Birthday at the British Embassy, a seamless blend of protocol, pageantry, and BlueOcean precision.",
    },
    {
        slug: 'qatar-national-day',
        title: 'Qatar National Day Celebrations',
        category: 'Diplomatic Reception',
        location: 'Qatar Embassy, Cairo',
        year: '2025',
        partnershipBadge: '3 Trusted Editions',
        img: '/event photos/Qatar Embassy - National Day Event/Qatar_1.png',
        bgImg: '/event photos/Qatar Embassy - National Day Event/Qatar_1.png',
        heroImg: '/event photos/Qatar Embassy - National Day Event/qatar Photos/1Y6A4249.jpg',
        yearSections: [
            { year: '2025', video: '/event videos/Qatar Embassy - National Day Event/Qatar_national_day_celebration__2025.mp4' },
            { year: '2024', video: '/event videos/Qatar Embassy - National Day Event/Qatar_national_day_celebration__2024.mp4' },
            { year: '2022', video: '/event videos/Qatar Embassy - National Day Event/Qatar_national_day_celebration__2022.mp4' },
        ],
        gallery: [
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/031A4891.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/031A5032.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/1Y6A4249.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/1Y6A4336.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/1Y6A4351.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/1Y6A5141.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/5P3A4869.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/5P3A4910.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/5P3A5663.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/5P3A5681.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/5P3A5716.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/5P3A5741.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/5P3A5754.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/DSC03222.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/DSC03227.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/DSC03247.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/DSC03266.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/DSC03293.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/DSC03555.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/DSC03635.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/DSC03674.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/DSC03692.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/DSC03701.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/OMAR6407.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/OMAR6410.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/OMAR6637.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/OMAR6643.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/OMAR6843.jpg',
            '/event photos/Qatar Embassy - National Day Event/qatar Photos/OMAR7159.jpg',
            '/event photos/Qatar Embassy - National Day Event/Qatar_1.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_2.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_3.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_4.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_5.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_6.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_7.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_8.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_9.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_10.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_11.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_12.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_13.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_14.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_15.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_16.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_17.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_18.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_19.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_20.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_21.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_22.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_23.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_24.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_25.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_26.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_27.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_28.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_29.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_30.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_31.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_32.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_33.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_34.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_35.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_36.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_37.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_38.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_39.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_40.png',
            '/event photos/Qatar Embassy - National Day Event/Qatar_41.png',
        ],
        description: 'Three editions of Qatar\'s most distinguished national celebration — an evening of diplomacy, culture, and pride produced with the precision and elegance the occasion demands.',
    },
    {
        slug: 'medfest',
        title: 'Medfest Film Festival',
        partnershipBadge: '3 Consecutive Editions',
        category: 'Film Festival',
        location: 'Cairo — AUC Tahrir Square',
        year: '2025',
        img: '/event photos/Medfest 5th/MagedHelal-Studio-708_web.jpg',
        imgScale: 1.2,
        imgPosition: 'center 10%',
        bgImg: '/event photos/Medfest 5th/image26_web.jpg',
        heroImg: '/event photos/Medfest 5th/MagedHelal-Studio-1279_web.jpg',
        yearSections: [
            { year: '7th', video: '/event videos/Medfest 5th/MEDFEST-2025-Recap-1.mp4' },
            { year: '6th', video: '/event videos/Medfest 5th/Medfest_6th.mp4' },
            { year: '5th', video: '/event videos/Medfest 5th/MEDFEST.mp4' },
        ],
        gallery: [
            // ── Entrance & Red Carpet ──
            '/event photos/Medfest 5th/image89.jpeg',
            '/event photos/Medfest 5th/image90.jpeg',
            '/event photos/Medfest 5th/image91.jpeg',
            '/event photos/Medfest 5th/image93.jpeg',
            '/event photos/Medfest 5th/image94.jpeg',
            '/event photos/Medfest 5th/image95.jpeg',
            '/event photos/Medfest 5th/image96.jpeg',
            '/event photos/Medfest 5th/image97.jpeg',
            '/event photos/Medfest 5th/image98.jpeg',
            '/event photos/Medfest 5th/image99.jpeg',
            '/event photos/Medfest 5th/image100.jpeg',
            '/event photos/Medfest 5th/image101.jpeg',
            '/event photos/Medfest 5th/image102.jpeg',
            '/event photos/Medfest 5th/image103.jpeg',
            '/event photos/Medfest 5th/image26.png',
            // ── Professional Photography ──
            '/event photos/Medfest 5th/MagedHelal-Studio-071.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-090.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-113.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-150.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-151.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-157.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-174.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-201.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-257.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-275.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-369.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-449.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-462.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-467.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-478.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-484.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-521.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-706.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-708.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-711.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-723.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-829.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-843.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-856.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-926.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-928.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-945.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-951.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-956.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-967.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-982.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-985.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-02130.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-02146.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-02151.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1000.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1015.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1016.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1021.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1028.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1033.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1047.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1091.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1100.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1108.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1115.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1119.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1126.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1136.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1151.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1152.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1170.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1279.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1354.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1359.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1380.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1417.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1438.jpg',
            '/event photos/Medfest 5th/MagedHelal-Studio-1446.jpg',
            // ── DSC Series ──
            '/event photos/Medfest 5th/DSC07146.JPG',
            '/event photos/Medfest 5th/DSC07156.JPG',
            '/event photos/Medfest 5th/DSC07258.JPG',
            '/event photos/Medfest 5th/DSC07364.JPG',
            '/event photos/Medfest 5th/DSC07391.JPG',
            '/event photos/Medfest 5th/DSC07545.JPG',
            '/event photos/Medfest 5th/DSC07548.JPG',
            '/event photos/Medfest 5th/DSC07549.JPG',
            '/event photos/Medfest 5th/DSC07560.JPG',
            '/event photos/Medfest 5th/DSC07561.JPG',
            '/event photos/Medfest 5th/DSC07565.JPG',
            '/event photos/Medfest 5th/DSC07575.JPG',
            '/event photos/Medfest 5th/DSC07597.JPG',
            '/event photos/Medfest 5th/DSC07680.JPG',
            '/event photos/Medfest 5th/DSC07685.JPG',
            '/event photos/Medfest 5th/DSC07710.JPG',
            '/event photos/Medfest 5th/DSC07716.JPG',
            '/event photos/Medfest 5th/DSC07721.JPG',
            '/event photos/Medfest 5th/DSC07750.JPG',
            '/event photos/Medfest 5th/DSC07767.JPG',
            '/event photos/Medfest 5th/DSC07774.JPG',
            '/event photos/Medfest 5th/DSC07812.JPG',
            '/event photos/Medfest 5th/DSC07818.JPG',
            '/event photos/Medfest 5th/DSC07840.JPG',
            '/event photos/Medfest 5th/DSC07907.JPG',
            '/event photos/Medfest 5th/DSC07911.JPG',
            '/event photos/Medfest 5th/DSC07914.JPG',
            '/event photos/Medfest 5th/DSC07928.JPG',
            '/event photos/Medfest 5th/DSC07934.JPG',
            '/event photos/Medfest 5th/DSC07989.JPG',
            '/event photos/Medfest 5th/DSC08000.JPG',
            '/event photos/Medfest 5th/DSC08008.JPG',
            '/event photos/Medfest 5th/DSC08024.JPG',
        ],
        description: "Three editions of Medfest — Egypt's premier medical film festival — staged inside the historic El Manesterly Theatre, where healthcare storytelling meets cinematic artistry on a grand scale.",
    },
    {
        slug: 'signal',
        title: 'Signal × UNICEF',
        category: 'Project Launch',
        location: 'Cairo Citadel',
        year: '2025',
        img: '/event photos/Signal/0P9A4526.jpg',
        heroImg: '/event photos/Signal/6c30aa53-89ee-4821-9a46-262af73ff114.JPG',
        gallery: [
            // ── Video ──
            '/event videos/Signal/signal event Video.mp4',
            // ── Branding & Entrance ──
            '/event photos/Signal/NS__6763.jpg',
            '/event photos/Signal/6c30aa53-89ee-4821-9a46-262af73ff114.JPG',
            '/event photos/Signal/7908d696-a2ab-4229-b1e7-ed506dd6602a.JPG',
            // ── Birdeye & Venue ──
            '/event photos/Signal/f03c112a-74bd-4b0f-af4c-f36887902383.JPG',
            '/event photos/Signal/NS__6714.jpg',
            '/event photos/Signal/0P9A4224.jpg',
            // ── Red Carpet ──
            '/event photos/Signal/0P9A4257.jpg',
            '/event photos/Signal/0P9A4260.jpg',
            '/event photos/Signal/0P9A4340.jpg',
            // ── Activations ──
            '/event photos/Signal/DSC00025.jpg',
            '/event photos/Signal/NS__6891.jpg',
            '/event photos/Signal/NS__6898.jpg',
            // ── Stage & Ceremony ──
            '/event photos/Signal/7E4A9477.jpg',
            '/event photos/Signal/NS__6927.jpg',
            '/event photos/Signal/0P9A4508.jpg',
            // ── Kids Performance & Finale ──
            '/event photos/Signal/NS__7129.jpg',
            '/event photos/Signal/0P9A4526.jpg',
            '/event photos/Signal/0P9A4110.jpg',
        ],
        description: "A landmark oral health activation produced for Signal in partnership with UNICEF and the FDI World Dental Federation — set against the iconic backdrop of the Cairo Citadel, uniting communities, celebrities, and children in a celebration of wellness.",
    },
    {
        slug: 'shell-stlc',
        title: 'Shell STLC Event',
        category: 'Sales Conference',
        location: 'Cairo Hyatt',
        year: '2024',
        img: '/event photos/Shell STLC/image155-2_web.jpg',
        heroImg: '/event photos/Shell STLC/image153.jpeg',
        gallery: [
            // ── Video ──
            '/event videos/Shell STLC/shell Long Version.mp4',
            // ── Branding & Entrance ──
            '/event photos/Shell STLC/image157.jpeg',
            '/event photos/Shell STLC/image158.jpeg',
            '/event photos/Shell STLC/image153.jpeg',
            '/event photos/Shell STLC/image159_web.jpg',
            // ── Stage & Presentations ──
            '/event photos/Shell STLC/image154-2_web.jpg',
            '/event photos/Shell STLC/image155-2_web.jpg',
            '/event photos/Shell STLC/image156.jpeg',
            // ── Conference Sessions ──
            '/event photos/Shell STLC/DSC00526_web.jpg',
            '/event photos/Shell STLC/DSC00535_web.jpg',
            '/event photos/Shell STLC/DSC00559_web.jpg',
            '/event photos/Shell STLC/DSC00860_web.jpg',
            '/event photos/Shell STLC/DSC00865_web.jpg',
            '/event photos/Shell STLC/DSC00874_web.jpg',
            '/event photos/Shell STLC/DSC00919_web.jpg',
            // ── 076B Series ──
            '/event photos/Shell STLC/076B0922_web.jpg',
            '/event photos/Shell STLC/076B0970_web.jpg',
            '/event photos/Shell STLC/076B1129_web.jpg',
            '/event photos/Shell STLC/076B1255_web.jpg',
            '/event photos/Shell STLC/076B1300_web.jpg',
            '/event photos/Shell STLC/076B1426_web.jpg',
            // ── GRGS Series ──
            '/event photos/Shell STLC/GRGS0070_web.jpg',
            '/event photos/Shell STLC/GRGS9511_web.jpg',
            '/event photos/Shell STLC/GRGS9530_web.jpg',
            '/event photos/Shell STLC/GRGS9587_web.jpg',
            '/event photos/Shell STLC/GRGS9592_web.jpg',
            '/event photos/Shell STLC/GRGS9598_web.jpg',
            '/event photos/Shell STLC/GRGS9717_web.jpg',
            // ── Activations & Networking ──
            '/event photos/Shell STLC/image160.jpeg',
            '/event photos/Shell STLC/image161.jpeg',
            '/event photos/Shell STLC/image162.jpeg',
            '/event photos/Shell STLC/image163.jpeg',
            '/event photos/Shell STLC/image164.jpeg',
            '/event photos/Shell STLC/image165.jpeg',
            // ── Venue, Catering & Awards ──
            '/event photos/Shell STLC/image166.jpeg',
            '/event photos/Shell STLC/image167.jpeg',
            '/event photos/Shell STLC/image168.jpeg',
        ],
        description: "Shell's 2024 Short Term Lubricants Conference — a meticulously crafted corporate gathering at Cairo's Hyatt that brought together distributors and leaders across the region for strategy, recognition, and connection.",
    },
    {
        slug: 'saxenda',
        title: 'Saxenda 4th Anniversary',
        category: 'Pharma',
        location: 'Cairo — JW Marriott',
        year: '2025',
        img: '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-09.png',
        heroImg: '/event photos/Saxenda 4th Annivesrasy/image74.jpeg',
        gallery: [
            // ── Video ──
            '/event videos/Saxenda 4th Annivesrasy/Saxenda 4th Video.mp4',
            // ── Entrance & Branding ──
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-06.png',
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-01.png',
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-02.png',
            // ── Corridor & Identity ──
            '/event photos/Saxenda 4th Annivesrasy/image76.jpeg',
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-04.png',
            '/event photos/Saxenda 4th Annivesrasy/image82.jpeg',
            // ── 4th Anniversary Installations ──
            '/event photos/Saxenda 4th Annivesrasy/image80.jpeg',
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-03.png',
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-05.png',
            // ── Stage & Ballroom ──
            '/event photos/Saxenda 4th Annivesrasy/image74.jpeg',
            '/event photos/Saxenda 4th Annivesrasy/image86.jpeg',
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-11.png',
            // ── Stage Moments ──
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-09.png',
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-14.png',
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-15.png',
            // ── Production & Atmosphere ──
            '/event photos/Saxenda 4th Annivesrasy/image83.jpeg',
            '/event photos/Saxenda 4th Annivesrasy/image84.jpeg',
            '/event photos/Saxenda 4th Annivesrasy/image85.jpeg',
            // ── Night & Finale ──
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-16.png',
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-17.png',
            '/event photos/Saxenda 4th Annivesrasy/image88.jpeg',
            // ── Additional ──
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-20.png',
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-21.png',
            '/event photos/Saxenda 4th Annivesrasy/saxenda-photo-22.png',
        ],
        description: "A spectacular anniversary gala celebrating four years of Saxenda in the Egyptian market — an immersive neon-and-purple world of performance, storytelling, and celebration produced for Novo Nordisk.",
    },
    {
        slug: 'main-marks',
        title: 'Main Marks — Moray',
        category: 'Real Estate',
        location: 'Cairo',
        year: '2025',
        img: '/event photos/Main Marks/image245.jpeg',
        heroImg: '/event photos/Main Marks/image255.jpeg',
        gallery: [
            // ── Video ──
            '/event videos/Main Marks/main_marks_broker event.mp4',
            // ── Branding & Identity ──
            '/event photos/Main Marks/image245.jpeg',
            '/event photos/Main Marks/image246.jpeg',
            '/event photos/Main Marks/image247.jpeg',
            // ── Entrance & Setup ──
            '/event photos/Main Marks/image248.jpeg',
            '/event photos/Main Marks/image249.jpeg',
            '/event photos/Main Marks/image250.jpeg',
            // ── Stage & Presentations ──
            '/event photos/Main Marks/image251.jpeg',
            '/event photos/Main Marks/image252.jpeg',
            '/event photos/Main Marks/image253.jpeg',
            // ── Speakers & Panel ──
            '/event photos/Main Marks/image255.jpeg',
            '/event photos/Main Marks/image256.jpeg',
            '/event photos/Main Marks/image257.jpeg',
            // ── Audience & Networking ──
            '/event photos/Main Marks/image258.jpeg',
            '/event photos/Main Marks/image259.jpeg',
            '/event photos/Main Marks/image260.jpeg',
            // ── Crowd & Atmosphere ──
            '/event photos/Main Marks/image261.jpeg',
            '/event photos/Main Marks/image262.jpeg',
            '/event photos/Main Marks/image263.jpeg',
            // ── Grand Reveal — full-width sequence (last 4) ──
            '/event photos/Main Marks/image264.jpeg',
            '/event photos/Main Marks/image265.jpeg',
            '/event photos/Main Marks/image266.jpeg',
            '/event photos/Main Marks/image267.jpeg',
        ],
        description: "A high-energy broker launch event for Main Marks presenting the MORAY project — an immersive dark-production spectacle that brought real estate brokers together inside a world-class theatrical staging with dramatic lighting and a powerful brand reveal.",
    },
    {
        slug: 'direction-white',
        title: 'Direction White — Arabella',
        category: 'Real Estate',
        location: 'Cairo — InterContinental',
        year: '2025',
        img: '/event photos/Direction White/image229.jpeg',
        imgPosition: 'center 52%',
        imgScale: 1.6,
        heroImg: '/event photos/Direction White/image243.jpeg',
        gallery: [
            // ── Branding & Entrance ──
            '/event photos/Direction White/image229.jpeg',
            '/event photos/Direction White/image230.jpeg',
            '/event photos/Direction White/image231.jpeg',
            // ── White Installations & Activations ──
            '/event photos/Direction White/image232.jpeg',
            '/event photos/Direction White/image233.jpeg',
            '/event photos/Direction White/image234.jpeg',
            // ── Stage & Production ──
            '/event photos/Direction White/image235.jpeg',
            '/event photos/Direction White/image236.jpeg',
            '/event photos/Direction White/image237.jpeg',
            // ── Venue & Tent ──
            '/event photos/Direction White/image238.jpeg',
            '/event photos/Direction White/image239.jpeg',
            '/event photos/Direction White/image241.jpeg',
            // ── Grand Reveal — full-width sequence (last 4) ──
            '/event photos/Direction White/image242.jpeg',
            '/event photos/Direction White/image243.jpeg',
            '/event photos/Direction White/image244.jpeg',
            '/event photos/Direction White/image82.png',
        ],
        description: "The launch of Direction White's Arabella — a sun-soaked coastal real estate project unveiled through a refined all-white event concept at the InterContinental, blending sculptural art, live music, and an immersive brand world.",
    },
    {
        slug: 'manaj',
        title: 'Manaj — Blanks',
        category: 'Real Estate',
        location: 'Cairo',
        year: '2025',
        img: '/event photos/Manaj/image309.jpeg',
        heroImg: '/event photos/Manaj/image314.jpeg',
        gallery: [
            // ── Entrance & Branding ──
            '/event photos/Manaj/image303.jpeg',
            '/event photos/Manaj/image304.jpeg',
            '/event photos/Manaj/image305.jpeg',
            // ── Blanks Installations ──
            '/event photos/Manaj/image306.jpeg',
            '/event photos/Manaj/image307.jpeg',
            '/event photos/Manaj/image308.jpeg',
            // ── Stage & Presentation ──
            '/event photos/Manaj/image309.jpeg',
            '/event photos/Manaj/image310.jpeg',
            '/event photos/Manaj/image311.jpeg',
            // ── Grand Reveal — full-width sequence (last 4) ──
            '/event photos/Manaj/image312.jpeg',
            '/event photos/Manaj/image313.jpeg',
            '/event photos/Manaj/image314.jpeg',
            '/event photos/Manaj/image302.jpeg',
        ],
        description: "The launch of Manaj's 'Blanks' — a sanctuary real estate concept unveiled through a cinematic dark-production event, where architectural minimalism met dramatic laser shows and immersive brand storytelling in Cairo's most exclusive ballroom.",
    },
    {
        slug: 'mondelez',
        title: 'Mondelez International',
        category: 'Sales Event',
        location: 'Cairo — Sports Arena',
        year: '2025',
        img: '/event photos/Mondelez/Card.png',
        heroImg: '/event photos/Mondelez/image315.jpeg',
        gallery: [
            // ── Stage & Opening ──
            '/event photos/Mondelez/image315.jpeg',
            '/event photos/Mondelez/image316.jpeg',
            '/event photos/Mondelez/image317.jpeg',
            // ── Arena & Crowd ──
            '/event photos/Mondelez/image318.jpeg',
            '/event photos/Mondelez/image319.jpeg',
            '/event photos/Mondelez/image320.jpeg',
            // ── Performances ──
            '/event photos/Mondelez/image321.jpeg',
            '/event photos/Mondelez/image322.jpeg',
            '/event photos/Mondelez/image323.jpeg',
            // ── Brand Activations ──
            '/event photos/Mondelez/image324.jpeg',
            '/event photos/Mondelez/image325.jpeg',
            '/event photos/Mondelez/image326.jpeg',
            // ── Grand Finale — full-width sequence (last 4) ──
            '/event photos/Mondelez/image327.jpeg',
            '/event photos/Mondelez/image328.jpeg',
            '/event photos/Mondelez/image329.jpeg',
            '/event photos/Mondelez/image330.jpeg',
        ],
        description: "Mondelez International's 'Snacking Made Right' — a spectacular sales conference and festival staged inside a packed Cairo sports arena, bringing together thousands of distributors and sales teams for an unforgettable evening of recognition, live entertainment, and brand celebration.",
    },
    {
        slug: 'revolve',
        title: 'Revolve — Town Writers',
        category: 'Real Estate',
        location: 'Cairo',
        year: '2025',
        img: '/event photos/Revolve - Town Writers/image297.jpeg',
        heroImg: '/event photos/Revolve - Town Writers/image281.jpeg',
        gallery: [
            // ── Entrance & Branding ──
            '/event photos/Revolve - Town Writers/image281.jpeg',
            '/event photos/Revolve - Town Writers/image282.jpeg',
            '/event photos/Revolve - Town Writers/image284.jpeg',
            // ── Activations & Performers ──
            '/event photos/Revolve - Town Writers/image285.jpeg',
            '/event photos/Revolve - Town Writers/image286.jpeg',
            '/event photos/Revolve - Town Writers/image287.jpeg',
            // ── Stage & Production ──
            '/event photos/Revolve - Town Writers/image288.jpeg',
            '/event photos/Revolve - Town Writers/image289.jpeg',
            '/event photos/Revolve - Town Writers/image290.jpeg',
            // ── Presentations & Speakers ──
            '/event photos/Revolve - Town Writers/image291.jpeg',
            '/event photos/Revolve - Town Writers/image292.jpeg',
            '/event photos/Revolve - Town Writers/image293.jpeg',
            // ── Crowd & Atmosphere ──
            '/event photos/Revolve - Town Writers/image294.jpeg',
            '/event photos/Revolve - Town Writers/image295.jpeg',
            '/event photos/Revolve - Town Writers/image296.jpeg',
            // ── Grand Finale — full-width sequence (last 4) ──
            '/event photos/Revolve - Town Writers/image297.jpeg',
            '/event photos/Revolve - Town Writers/image298.jpeg',
            '/event photos/Revolve - Town Writers/image299.jpeg',
            '/event photos/Revolve - Town Writers/image300.jpeg',
        ],
        description: "Revolve — Town Writers' broker launch event — a theatrical spectacle under a grand chandelier ballroom where 'Everything Revolves Around You', bringing Egypt's top real estate brokers into a world of immersive brand storytelling and live performance.",
    },
    {
        slug: 'obsidier',
        title: 'Obsidier Towers',
        category: 'Real Estate',
        location: 'Cairo — Dubai Developments',
        year: '2025',
        img: '/event photos/Obsidier Towers/image216.jpeg',
        heroImg: '/event photos/Obsidier Towers/image225.jpeg',
        gallery: [
            // ── Video ──
            '/event videos/Obsidier Towers/dubai_development____obsidier_launch_event.mp4',
            // ── Architectural Identity ──
            '/event photos/Obsidier Towers/image209.jpeg',
            '/event photos/Obsidier Towers/image210.jpeg',
            '/event photos/Obsidier Towers/image211.jpeg',
            // ── Venue & Stage Setup ──
            '/event photos/Obsidier Towers/image212.jpeg',
            '/event photos/Obsidier Towers/image213.jpeg',
            '/event photos/Obsidier Towers/image214.jpeg',
            // ── Presentations ──
            '/event photos/Obsidier Towers/image215.jpeg',
            '/event photos/Obsidier Towers/image216.jpeg',
            '/event photos/Obsidier Towers/image217.jpeg',
            // ── Stage Moments ──
            '/event photos/Obsidier Towers/image218.jpeg',
            '/event photos/Obsidier Towers/image220.jpeg',
            '/event photos/Obsidier Towers/image221.jpeg',
            // ── Brand Details & Activations ──
            '/event photos/Obsidier Towers/image222.jpeg',
            '/event photos/Obsidier Towers/image223.jpeg',
            '/event photos/Obsidier Towers/image224.jpeg',
            // ── Atmosphere & Crowd ──
            '/event photos/Obsidier Towers/image225.jpeg',
            '/event photos/Obsidier Towers/image226.jpeg',
            '/event photos/Obsidier Towers/image227.jpeg',
            // ── Finale ──
            '/event photos/Obsidier Towers/image228.jpeg',
            '/event photos/Obsidier Towers/image78.png',
            '/event photos/Obsidier Towers/image79.png',
        ],
        description: "The launch of Obsidier Towers by Dubai Developments — a cinematic dark-production event forged in the philosophy of 'our origin is lava', where dramatic lighting, fog, and obsidian branding created an unforgettable reveal experience.",
    },
    {
        slug: 'egyptian-obesity-summit',
        title: 'Egyptian Obesity Summit',
        category: 'Medical Congress',
        location: 'Cairo — Dusit Lake View',
        year: '2025',
        img: '/event photos/Egyptian Obesity Summit/image59.png',
        imgScale: 1.3,
        heroImg: '/event photos/Egyptian Obesity Summit/image59.png',
        gallery: [
            // ── Video ──
            '/event videos/Egyptian Obesity Summit/novo_nordisk____eos_3rd.mp4',
            // ── Identity & Entrance ──
            '/event photos/Egyptian Obesity Summit/eos-photo-01.png',
            '/event photos/Egyptian Obesity Summit/eos-photo-02.png',
            '/event photos/Egyptian Obesity Summit/eos-photo-03.png',
            // ── Stage & Opening ──
            '/event photos/Egyptian Obesity Summit/image170.jpeg',
            '/event photos/Egyptian Obesity Summit/eos-photo-04.png',
            '/event photos/Egyptian Obesity Summit/eos-photo-05.png',
            // ── Keynote Speakers ──
            '/event photos/Egyptian Obesity Summit/image174.jpeg',
            '/event photos/Egyptian Obesity Summit/eos-photo-06.png',
            '/event photos/Egyptian Obesity Summit/image171.jpeg',
            // ── Panel Discussions ──
            '/event photos/Egyptian Obesity Summit/image178.jpeg',
            '/event photos/Egyptian Obesity Summit/eos-photo-07.png',
            '/event photos/Egyptian Obesity Summit/eos-photo-08.png',
            // ── Conference Sessions ──
            '/event photos/Egyptian Obesity Summit/eos-photo-09.png',
            '/event photos/Egyptian Obesity Summit/eos-photo-10.png',
            '/event photos/Egyptian Obesity Summit/image172.jpeg',
            // ── Brand & Activations ──
            '/event photos/Egyptian Obesity Summit/image59.png',
            '/event photos/Egyptian Obesity Summit/eos-photo-11.png',
            '/event photos/Egyptian Obesity Summit/image173.jpeg',
            // ── Scientific Sessions ──
            '/event photos/Egyptian Obesity Summit/image175.jpeg',
            '/event photos/Egyptian Obesity Summit/image176.jpeg',
            '/event photos/Egyptian Obesity Summit/image177.jpeg',
            // ── Networking & Details ──
            '/event photos/Egyptian Obesity Summit/image179.jpeg',
            '/event photos/Egyptian Obesity Summit/image180.jpeg',
            '/event photos/Egyptian Obesity Summit/image181.jpeg',
            // ── Grand Finale — full-width sequence (last 4) ──
            '/event photos/Egyptian Obesity Summit/image184.jpeg',
            '/event photos/Egyptian Obesity Summit/image185.jpeg',
            '/event photos/Egyptian Obesity Summit/image186.jpeg',
            '/event photos/Egyptian Obesity Summit/eos-photo-12.png',
        ],
        description: "The 3rd Egyptian Obesity Summit — 'Driving Change in Obesity' — a landmark medical congress produced for Novo Nordisk, uniting Egypt's top healthcare professionals on a world-class stage for science, dialogue, and inspiration.",
    },
    {
        slug: 'notion',
        title: 'Notion — Town Writers',
        category: 'Real Estate',
        location: 'Cairo',
        year: '2024',
        img: '/event photos/Notion/DSC04808.JPG',
        imgPosition: '22% 65%',
        imgScale: 1.6,
        heroImg: '/event photos/Notion/image34.png',
        gallery: [
            // ── Videos ──
            '/event videos/Notion/Notion_Video_1.mp4',
            '/event videos/Notion/Notion_Video_2.mp4',
            '/event videos/Notion/Notion_Video_3.mp4',
            // ── Campaign & Creative ──
            '/event photos/Notion/image34.png',
            '/event photos/Notion/image35.png',
            '/event photos/Notion/image36.png',
            // ── Brand Identity ──
            '/event photos/Notion/image37.png',
            '/event photos/Notion/image39.png',
            '/event photos/Notion/image40.png',
            // ── Activations — Installations ──
            '/event photos/Notion/image41.png',
            '/event photos/Notion/image42.png',
            '/event photos/Notion/image43.png',
            // ── Details & Merch ──
            '/event photos/Notion/image44.png',
            '/event photos/Notion/image45.png',
            '/event photos/Notion/image46.png',
            // ── Venue & Experience ──
            '/event photos/Notion/image47.png',
            '/event photos/Notion/image48.png',
            '/event photos/Notion/image49.png',
            // ── Stage & Opening ──
            '/event photos/Notion/image120.jpeg',
            '/event photos/Notion/image121.jpeg',
            '/event photos/Notion/image122.jpeg',
            // ── Presentations ──
            '/event photos/Notion/image123.jpeg',
            '/event photos/Notion/image124.jpeg',
            '/event photos/Notion/image125.jpeg',
            // ── Crowd & Energy ──
            '/event photos/Notion/image126.jpeg',
            '/event photos/Notion/image127.jpeg',
            '/event photos/Notion/image128.jpeg',
            // ── Sessions ──
            '/event photos/Notion/image130.jpeg',
            '/event photos/Notion/image131.jpeg',
            '/event photos/Notion/image132.jpeg',
            // ── Speakers ──
            '/event photos/Notion/image133.jpeg',
            '/event photos/Notion/image134.jpeg',
            '/event photos/Notion/image136.jpeg',
            // ── Networking ──
            '/event photos/Notion/image139.jpeg',
            '/event photos/Notion/image140.jpeg',
            '/event photos/Notion/image141.jpeg',
            // ── Grand Finale — full-width sequence (last 4) ──
            '/event photos/Notion/DSC04808.JPG',
            '/event photos/Notion/DSC04817.JPG',
            '/event photos/Notion/DSC05585.JPG',
            '/event photos/Notion/image50.png',
        ],
        description: "Notion — Town Writers' bold youth real estate project launch — 'Not Your Ordinary Gated Community' — a high-energy event world built for Egypt's dynamic generation, where vibrant brand activations, live sessions, and fearless creative direction made every moment unforgettable.",
    },
    {
        slug: 'lng-1000',
        title: 'Egyptian LNG — 1000 Cargos',
        category: 'Milestone Celebration',
        location: 'Cairo',
        year: '2022',
        img: '/event photos/LNG 1000 Cargo Celebration/Trophy_LNG_2.JPG',
        heroImg: '/event photos/LNG 1000 Cargo Celebration/LNGG.png',
        gallery: [
            // ── Entrance & Branding ──
            '/event photos/LNG 1000 Cargo Celebration/ASM09177.jpg',
            '/event photos/LNG 1000 Cargo Celebration/ASM09182.jpeg',
            '/event photos/LNG 1000 Cargo Celebration/ASM09190.jpeg',
            // ── Stage & Ceremony ──
            '/event photos/LNG 1000 Cargo Celebration/LNGG.png',
            '/event photos/LNG 1000 Cargo Celebration/ASM09553.png',
            '/event photos/LNG 1000 Cargo Celebration/ASM00016.png',
            // ── Speakers & VIPs ──
            '/event photos/LNG 1000 Cargo Celebration/MF_03408.png',
            '/event photos/LNG 1000 Cargo Celebration/MF_03428.jpg',
            '/event photos/LNG 1000 Cargo Celebration/MF_03433.jpeg',
            // ── Milestone Reveal — full-width sequence (last 4) ──
            '/event photos/LNG 1000 Cargo Celebration/MF_03972.png',
            '/event photos/LNG 1000 Cargo Celebration/MF_04076.png',
            '/event photos/LNG 1000 Cargo Celebration/Trophy_LNG.jpeg',
            '/event photos/LNG 1000 Cargo Celebration/Trophy_LNG_2.JPG',
        ],
        description: "Egyptian LNG's 1000th Cargo milestone celebration — a landmark gala marking a historic achievement in Egypt's energy sector, commemorated through an elegant ceremony, a VIP button-press moment, and a bespoke commemorative trophy for one of Egypt's most significant industrial milestones.",
    },
]

export function getEventBySlug(slug: string): EventData | undefined {
    return events.find((e) => e.slug === slug)
}
